export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGOUT = "LOGOUT";

export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";

export const POST_FAVORITE_MOVIE_SUCCESS = "POST_FAVORITE_MOVIE_SUCCESS";
export const POST_FAVORITE_MOVIE_FAIL = "POST_FAVORITE_MOVIE_FAIL";

export const POST_WATCHLATER_MOVIE_SUCCESS = "POST_WATCHLATER_MOVIE_SUCCESS";
export const POST_WATCHLATER_MOVIE_FAIL = "POST_WATCHLATER_MOVIE_FAIL";

export const UPDATE_FAVORITE_MOVIES_ATTEMPT = "UPDATE_FAVORITE_MOVIES_ATTEMPT";
export const UPDATE_FAVORITE_MOVIES_SUCCESS = "UPDATE_FAVORITE_MOVIES_SUCCESS";
export const UPDATE_WATCHLATER_MOVIES_ATTEMPT =
  "UPDATE_WATCHLATER_MOVIES_ATTEMPT";
export const UPDATE_WATCHLATER_MOVIES_SUCCESS =
  "UPDATE_WATCHLATER_MOVIES_SUCCESS";

export const DELETE_FAVORITE_MOVIE_ATTEMPT = "DELETE_FAVORITE_MOVIE_ATTEMPT";
export const DELETE_FAVORITE_MOVIE_SUCCESS = "DELETE_FAVORITE_MOVIE_SUCCESS";
export const DELETE_FAVORITE_MOVIE_FAIL = "DELETE_FAVORITE_MOVIE_FAIL";
